[package]
name = "api-tpl-rs"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "api", "cmd", "setting", "crypto", "entity", "util"]

[dependencies]
tokio = { version = "1", features = ["full"] }

# workspace modules
api = { path = "api" }
cmd = { path = "cmd" }
setting = { path = "setting" }
